# Site settings
title: kuara
email: kuara@pinimar.tech
url: https://kuara.pinimar.tech
description: "Empowering digital marketers with their ad campaign data, all the way from API connections to a visual self-service exploratory interface."
keywords: "martech, marketing data, data, digital marketing, ads, digital ads, ad reporting"
skills: "Finally, an end-to-end marketing data solution"
meta_author: Bruno Pini

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 505855 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: F0CFC5 #FD6E8A
  secondary-dark: 252927 #A2122F

# Footer settings
footer:
  copyright: pinimartec
  location: PINI MARTECH LTDA
  social: pinimar.tech
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/jekyll
  - title: linkedin
    url: https://linkedin.com/in/brunopini

# Postal address (add as many lines as necessary)
address:
  - line: 40.813.705/0001-42
  - line: São Paulo, Brazil

# Credits content
credits: 'Kuara is a marketing data product in early access and is owned by Pinimartec. Request a demo via our contact form.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
